spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: redefinirsenhasystem6@gmail.com
    password: fcvh fwwg bdcd uzms
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true  
  
  datasource:
    url: jdbc:postgresql://c3v5n5ajfopshl.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dsu8kd6t0ssp8
    username: u9eng25jdnb5k4
    password: p97b9ef25a5b7f88fd862fb8a9108603055d02a75b3341c5dce8ec584289948a7
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate:
        default_schema: public  
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8081

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    org.springframework.orm.jpa: DEBUG

spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true

gg:
  jte:
    developmentMode: true
    templateLocation: src/main/resources/jte
