spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: redefinirsenhasystem6@gmail.com
    password: fcvh fwwg bdcd uzms
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true

  datasource:
    url: jdbc:postgresql://localhost:5432/clinicabd
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8081

logging:
  level:
    org.hibernate: ERROR
    org.springframework.orm.jpa: DEBUG
    com.yourpackage: DEBUG

gg:
  jte:
    development-mode: false
    use-precompiled-templates: true
    templateLocation: src/main/resources/jte
