spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: redefinirsenhasystem6@gmail.com
    password: fcvh fwwg bdcd uzms
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://ec2-54-85-169-59.compute-1.amazonaws.com:5432/d2ecfd4emc36r5?sslmode=require}
    username: ${JDBC_DATABASE_USERNAME:ub446tlqv3veu2}
    password: ${JDBC_DATABASE_PASSWORD:pbd62f590a866764d8e90d92ea92ec70940d3d3503694a08f52f7f40cd7c1355a}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8081

logging:
  level:
    org.hibernate: ERROR
    org.springframework.orm.jpa: DEBUG
    com.yourpackage: DEBUG

gg:
  jte:
    development-mode: true
    templateLocation: src/main/resources/jte