spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: redefinirsenhasystem6@gmail.com
    password: fcvh fwwg bdcd uzms
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    url: ${JDBC_DATABASE_URL:${DATABASE_URL}}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate: INFO
    org.springframework: INFO
    com.yourpackage: DEBUG